pipeline {
  agent any

  environment {
    IMAGE_NAME = "erp-sales"
    IMAGE_TAG = "${env.BUILD_ID}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build WAR') {
      steps {
        sh 'mvn clean package'
      }
    }

    stage('Build Docker Image') {
      steps {
        sh 'docker build -t $IMAGE_NAME:$IMAGE_TAG .'
      }
    }

    stage('Run Container (optional)') {
      when {
        expression { return false }  // set to true if you want to auto-run locally
      }
      steps {
        sh 'docker run -d -p 8080:8080 $IMAGE_NAME:$IMAGE_TAG'
      }
    }
  }
}
