pipeline {
  agent any

  environment {
    AWS_REGION = "ap-southeast-2"
    ACCOUNT_ID = "457320695561"
    IMAGE_NAME = "erp-sales"
    ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}"
    IMAGE_TAG = "${BUILD_NUMBER}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build and Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'myjenkinsAWSuser', usernameVariable: 'AWS_ACCESS_KEY_ID', passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          dir('erp-sales') {
            sh "mvn clean package"
            sh "aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}"
            sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            sh "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}"
            sh "docker push ${ECR_REPO}:${IMAGE_TAG}"
          }
        }
      }
    }
  }
}
