pipeline {
  agent any

  tools {
    maven 'maven-3.8.1'
  }

  environment {
    IMAGE_NAME = "erp-sales"
    AWS_REGION = "ap-southeast-2"
    ACCOUNT_ID = "457320695561"
    ECR_REPO = "${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_NAME}"
    IMAGE_TAG = "${BUILD_ID}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build WAR') {
      steps {
        dir('erp-sales') {
          sh 'mvn clean package'
        }
      }
    }

    stage('Build Docker Image') {
      steps {
        dir('erp-sales') {
          sh 'docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .'
          sh 'docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${ECR_REPO}:${IMAGE_TAG}'
        }
      }
    }

    stage('Push to ECR') {
      steps {
        dir('erp-sales') {
          sh 'aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO'
          sh 'docker push ${ECR_REPO}:${IMAGE_TAG}'
        }
      }
    }
  }
}
